# Generated by Django 4.0.4 on 2022-05-03 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='categora',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 18, 19, 14, 520630, tzinfo=utc)),
        ),
    ]
